### ISSUE TITLE
Security Contact Requested

### ISSUE THREAD

**Issue by prodigysml** [Accenture/mercury#13]
@n33dle and I found a security vulnerability within the mercury project. We were hoping to get a core maintainer's contact details to responsibly disclose this vulnerability.

**Comment by ericcwlaw** [comment]
thanks for your message. This issue is closed due to lack of specific details.

**Comment by n33dle** [comment]
Hi @ericcwlaw - we're after some contact details to responsibly disclose a security vulnerability within this mercury project.

**Comment by ericcwlaw** [comment]
@n33dle @prodigysml Thank you so much for pointing out the Xml External Entity (XXE) security vulnerability and providing your recommendation. We have patched the SimpleXmlParser and finished regression tests. The patch will be added to the release v1.12.28.

**Comment by ericcwlaw** [comment]
code merged and verified
