### ISSUE TITLE
Support for Different Programming Environments?

### ISSUE THREAD

**Issue by petermetz** [Accenture/mercury#15]
Are there any plans to port/adapt this to support NodeJS?

**Comment by staszv** [comment]
@ericcwlaw can comment. I think Node was next on the list. Not sure the timeline.

**Comment by ericcwlaw** [comment]
@petermetz We are doing preparation work for NodeJS. It will be available as a language pack. We would leverage the native support of event loop and callback in NodeJS to make the port seamless. It is scheduled for release in the 2nd half of 2020.

**Comment by petermetz** [comment]
Thank you for the response! @ericcwlaw 
Just out of curiosity: Do you plan on using async hooks in any shape or form?
It's an *experimental* feature in the specs => https://nodejs.org/api/async_hooks.html

**Comment by acn-ericlaw** [comment]
Node.js is almost there. You can preview it here:
https://github.com/Accenture/mercury-nodejs

FYI we have tried async hooks library but it does not make it to the project yet.
