### ISSUE TITLE
Update README with short summary of Mercury

### ISSUE THREAD

**Issue by staszv** [Accenture/mercury#20]
This is a reminder to myself to do it and is based on an email thread with Eric a few months back.

Subtitle: User friendly reactive programming
 
Summary
•	Completely and **natively event driven**
•	Fully **open source** - Apache license - https://github.com/Accenture/mercury
•	**Simple configuration** and **simple AP**I hides all the scaffolding code
•	**Code naturally**, without worrying about asynchrony
•	Naturally code in **functional style**, which makes code very **portable**
•	**Mix and match languages** - currently Java and Python are supported, Node.js is WIP
•	Built-in **distributed tracing**
•	**Avoid going to the network** when running in the same process - shown to be a huge performance boost for latency critical applications
•	**Doesn't require all services to adopt**, will provide the same benefits to those that do adopt it
•	Learn and **start coding in less than 1 hr**
 
Benefits
•	**Developer productivity** - both authoring and maintenance
•	Improves **latency** of calls within the same process
•	Enables **fully reactive** implementations
•	**Scalability**
•	**Portability** of code between containers and clouds
•	**Observability** - know who is calling who and when, know where you are in workflows
•	Improves **future-proofing**: as better eventing libraries/frameworks/platforms become available, they can be brought in without changing a line of code
 
Features
•	Multiple languages supported - currently Java and Python are supported, Node.js is WIP
•	Plug in your favorite event stream. Popular ones are already supported.
•	Multiple eventing patterns supported - pub/sub, broadcast, command, etc.
•	REST APIs for event-based services
•	Built in distributed tracing
 
Gnarly Use Cases solved with Mercury
•	Workflows with event-based architecture, utilizing Saga pattern
•	Namespaces in event stream (e.g. Kafka)

**Comment by acn-ericlaw** [comment]
Please create a Pull Request. Thanks for the summary.

**Comment by acn-ericlaw** [comment]
We have incorporated your input into the README file in version 1.12.65. Thank you.

**Comment by staszv** [comment]
Thank you, Eric. That was fast!
